
version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: renttoolpro-wordpress
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: renttool123
      WORDPRESS_DB_NAME: renttoolpro
      JWT_SECRET_KEY: Cl@veSuperSecreta2025
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: renttoolpro-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: renttool123
      MYSQL_DATABASE: renttoolpro
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: renttoolpro-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: renttool123

volumes:
  wordpress_data:
  db_data:
